### ISSUE TITLE
Missing base image retries with "library" namespace

### ISSUE THREAD

**Issue by sosiouxme** [projectatomic/atomic-reactor#1008]
I came across this:

https://github.com/projectatomic/atomic-reactor/blob/d058ca2a6db25391f01f0c430c397b1891e558fa/atomic_reactor/plugins/pre_pull_base_image.py#L103-L108

I think the intent is to retry `example.com/spam` as `example.com/library/spam` but it looks to me like it will also retry `example.com/spam/eggs` as `example.com/library/eggs` which would be a bit surprising. Simple enough to fix, just checking if there's something I'm missing here.

**Comment by sosiouxme** [comment]
@twaugh @rcerven

**Comment by twaugh** [comment]
I think you're right.

**Comment by rcerven** [comment]
yop it should be adding 'library/' in front of namespace

**Comment by twaugh** [comment]
I think it should be leaving repository names alone if they already contain a 'namespace' part. The 'library' prefix is a bit of a historical thing really.
* [name] -> [list of names to try]
* example.com/spam -> example.com/spam, example.com/library/spam
* example.com/spam/eggs -> example.com/spam/eggs
