### ISSUE TITLE
Add support for kubernetes.io/dockerconfigjson secret type

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic-reactor#1019]
Currently only the ".dockercfg" format (kubernetes.io/dockercfg secret type) is supported for registry secrets.

We should add support for the newer ".docker/config.json" format (kubernetes.io/dockerconfigjson secret type). This is the only type [the upstream Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) even mention.

This could mean making a new DockerRegistryCredentials class which can handle either secret type, and converting all users of Dockercfg to the new class.

We could either auto-sense the secret type from the JSON file content, or inspect the secret to find out whether it is kubernetes.io/dockercfg or kubernetes.io/dockerconfigjson.

**Comment by cverna** [comment]
So this will be needed for Fedora, since in the docker-py version available in Fedora 27 and 28 is looking for this type of secret.

I am happy to work on this feature

**Comment by twaugh** [comment]
Fixed via #1021.
