### ISSUE TITLE
atomic-reactor doesn't support UTF-8 characters in the Dockerfiles

### ISSUE THREAD

**Issue by jcajka** [projectatomic/atomic-reactor#1072]
Trying to build https://src.fedoraproject.org/container/origin-base/blob/f28/f/Dockerfile (note Č in the label, I will probably change it to C to unblock myself) in the Fedora's OSBS/Koji fails. Log in attachment.
[orchestrator.log](https://github.com/projectatomic/atomic-reactor/files/2374999/orchestrator.log)

**Comment by twaugh** [comment]
It failed in store_metadata_in_osv3 because OpenShift doesn't allow us to store certain characters in annotations.

**Comment by jcajka** [comment]
@twaugh what can be done about it. Is there an upstream OpenShift issue?
IMO this is kind of important as we might have contributors that have name that are composed of UTF-8 chars an this is really silly.

**Comment by twaugh** [comment]
In fact on closer inspection this seems to be an issue with Koji's xmlrpc encoding. It is correctly escaping things like '<' (as `&lt;`) but not UTF-8 characters. It seems to use latin-1 for encoding.

Please file an issue at https://pagure.io/koji to track this.

**Comment by jcajka** [comment]
@twaugh done https://pagure.io/koji/issue/1208

**Comment by twaugh** [comment]
Thanks! I've subscribed to it.
