### ISSUE TITLE
introduce new plugin argument: `run_when_build_fails`

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-reactor#110]
Suggested by @goldmann

**Comment by goldmann** [comment]
I think the name of the variable should be different, maybe `run_always`?

**Comment by twaugh** [comment]
This ties in with the ability of a plugin to know whether the build has failed or not.

In #229 I've suggested a new class of plugin, 'exit', which will be run after everything else and even in the event of failure. Its constructor takes a bool indicating build success/failure.

What do you think of this approach? Should I redo it as `run_always`? (Harder to see how to implement that.)

**Comment by jpopelka** [comment]
Looking at https://github.com/projectatomic/atomic-reactor/pull/229#issuecomment-125263105 I think this should have already been closed, right ?

**Comment by twaugh** [comment]
Yes, thanks for spotting it.
