### ISSUE TITLE
Support "Standard Container/Application Identifiers"

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-reactor#116]
https://github.com/projectatomic/ContainerApplicationGenericLabels

Related #115

So the standard is set, let's implement.
# Updated Labels
- `Name` → `name`
- `Version` → `version`
- `Release` → `release`
- `Architecture` → `architecture`
- `Vendor` → `vendor`
- `Authoritative_Registry` → `authoritative-source`
- `BZComponent` → `com.redhat.component`
- `Build_Host` → `com.redhat.build-host`
# New Labels
- `build-date` — Date/Time image was built
  - we can populate this automatically
- `vcs-type` — The type of version control used by the container source. Generally one of git, hg, svn, bzr, cvs
  - we can populate this automatically (we'll take this from source type)
- `vcs-ref` — A 'reference' within the version control repository; e.g. a git commit, or a subversion branch
  - we can populate this automatically (we'll put commit ID there, not branch)
- `authoritative-source-url` — The authoritative location in which the image is published
  - **what should we put here?**
  - **is this different than `authoritative-source`?**
# Maintainer Controlled Labels

Not sure how to automate these: we should probably leave the responsibility to maintainers.
- `url` (Optional) — Url with more information on the image
- `summary` (Required) — Short Description of the image
- `description` (Optional) — Detailed description of the image
- `vcs-url` (Optional) — URL of the version control repository
- `distribution-scope` — Intended scope of distribution for image (see below for possible values)
  - **could this be automatically set to `authoritative-source-only`?**
- `changelog-url`
# Assert labels plugin

We should also check, if all required labels are set. **Which are required? Is this list complete?**
- `name`
- `version`
- `release`
- `architecture`
- `vendor`
- `authoritative-source`
- `com.redhat.component`
- `com.redhat.build-host`
- `build-date`
- `vcs-type`
- `vcs-ref`
- `authoritative-source`
- `description`

@pbabinca @aweiteka @riekrh @Zyzyx
Comment please.

**Comment by riekrh** [comment]
Please also see https://github.com/projectatomic/ContainerApplicationGenericLabels/tree/master/vendor/redhat as a reference to what is required.

**Comment by TomasTomecek** [comment]
@riekrh I've read that and it's still not perfectly clear to me.

**Comment by mmilata** [comment]
[Docker docs](https://docs.docker.com/userguide/labels-custom-metadata/) recommend the label keys to be from `[a-z0-9-.]+` and ContainerApplicationGenericLabels uses dashes as well so I'm assuming we should use dashes instead of underscores as well here.

**Comment by TomasTomecek** [comment]
@mmilata https://github.com/projectatomic/ContainerApplicationGenericLabels/pull/52

**Comment by TomasTomecek** [comment]
@mmilata I hope it's time to close this :)

**Comment by mmilata** [comment]
@TomasTomecek I'm afraid we're still not completely there:/

**Comment by goldmann** [comment]
How about now? :)

**Comment by twaugh** [comment]
Still not.

**Comment by lcarva** [comment]
@twaugh all done here?

**Comment by twaugh** [comment]
Yes!
