### ISSUE TITLE
make it configurable to specify base path of temp dir

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-reactor#153]
Since `/tmp` is on `tmpfs`, we lose everything once container finishes its job. We should be able to put it somewhere else, e.g. `/var`.

**Comment by TomasTomecek** [comment]
So `/tmp` in container is not on tmpfs at the moment. Not sure if it does make sense to do this.

**Comment by twaugh** [comment]
Do we actually lose anything then?

**Comment by TomasTomecek** [comment]
We should not and we should actually be able to `docker cp` the content. Closing then.
