### ISSUE TITLE
There is no atomic-reactor in Fedora pkgdb

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/atomic-reactor#213]
According to https://github.com/DBuildService/atomic-reactor/blob/master/README.md  , in Fedora we can install it as below. But it does not work as the RPM is not available in Fedora
```
$ yum install atomic-reactor python-atomic-reactor-koji
```

**Comment by ingvagabund** [comment]
@TomasTomecek , @bkabrda
Any plans to provide atomic-reactor via dock? Or rather create new review request?

**Comment by twaugh** [comment]
The packages are `dock` and `dock-koji` for the time being, until there is an Atomic Reactor release and package request.

**Comment by bkabrda** [comment]
Yeah, we're still waiting for Atomic Reactor to be moved under projectatomic GH org and then we'll handle all the release related stuff (hopefully this will happen within a week or so). That includes release on PyPI and new review request in Fedora. For the time being, please use `dock` and `dock-koji`. Thanks.

**Comment by jpopelka** [comment]
I can, but I think it'd be better if @bkabrda created the review request and I'll do the review itself.

**Comment by bkabrda** [comment]
I'll do that. Hopefully I'll manage to get to this until tomorrow.

**Comment by jpopelka** [comment]
Ok, I've checked the upstream spec file and I think there are several copy-paste errors.
@bkabrda see #232

**Comment by bkabrda** [comment]
@jpopelka good catches, merged. Thanks!

**Comment by bkabrda** [comment]
@LalatenduMohanty what Fedora releases do you want atomic-reactor in? I'm planning to put it just in rawhide for now, let me know if you need something else as well.

**Comment by LalatenduMohanty** [comment]
@bkabrda Are you planning to build it for EPEL? I think CentOS7 will be the platform on which I want to use it and maybe on Fedora22

**Comment by bkabrda** [comment]
@LalatenduMohanty Ok, I'll build also on F22 and EPEL 7.

**Comment by bkabrda** [comment]
Opened review request: https://bugzilla.redhat.com/show_bug.cgi?id=1246120 Feel free to take it and do the review.

**Comment by bkabrda** [comment]
Built for F22, F23 and rawhide. There's an issue in EPEL7 that makes atomic-reactor fail right now, so I haven't built it. Feel free to watch the referenced bugzilla to see when it gets fixed and atomic-reactor gets built in EPEL7. I'm closing this bug.

**Comment by LalatenduMohanty** [comment]
@bkabrda Looks like all the issues resolved in extras with respect to docker-python pkg. We should be able to build the RPM now. Lets try to build it
