### ISSUE TITLE
Move pulling base image into a plugin

### ISSUE THREAD

**Issue by mmilata** [projectatomic/atomic-reactor#218]
@pbabinca's proposal for scratch builds suggests that if there is `FROM xyz` in the Dockerfile then we should first try pulling `scratch-xyz` as a base image.

Moving the pulling logic into a plugin would make the implementation less messy since we need to know if the build is a scratch build, which can be easily passed as a parameter to the plugin.

**Comment by TomasTomecek** [comment]
I totally support having pulling logic in a plugin. But, here's the thing:

We should not break existing cli/python api.

I mean that right now api methods accept `parent_registry` argument. When we move the logic to plugin, we need to configure the new-to-be pulling plugin somehow (or maybe the plugin could read the value from workflow object?).

Therefore I think we need to [populate build json](https://github.com/DBuildService/atomic-reactor/blob/master/atomic_reactor/api.py#L50) with configuration for the new-to-be pulling plugin. (same case will be for pushing at some point)

Or maybe we don't need to. I'm not really sure what the best way for passing input configuration to plugins is.

**Comment by mmilata** [comment]
My w-i-p implementation takes `parent_registry` from the workflow object because I wanted to stay compatible with the current osbs client. However making `parent_registry` a plugin argument seems cleaner - I'll see if this can be done while retaining compatibility with older osbs, until we are sure everyone upgraded.

**Comment by TomasTomecek** [comment]
I'm totally fine when the plugin reads the value from workflow object
