### ISSUE TITLE
`atomic-reactor` fails on RHEL7 because of `python-requests` version

### ISSUE THREAD

**Issue by maxamillion** [projectatomic/atomic-reactor#225]
The version of python-requests that is in RHEL7 (core OS package set), and derivative distros (CentOS, et al), is too old.

I built an rpm from my git checkout with `tito build --test --builder mock --arg mock=epel-7-x86_64 --rpm` and then installed the resulting rpm. I get the following error:
```
[root@losbs ~]# atomic-reactor create-build-image --reactor-tarball-path /usr/share/atomic-reactor/atomic-reactor.tar.gz /usr/share/atomic-reactor/images/dockerhost-builder/ buildroot
Traceback (most recent call last):
  File "/usr/bin/atomic-reactor", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.2.1,<2.5.0

[root@losbs ~]# rpm -q python-requests
python-requests-1.1.0-8.el7.noarch
```

**Comment by TomasTomecek** [comment]
this is actually issue of `docker-py`; therefore we build `python-requests` and supply it from our own repo

**Comment by maxamillion** [comment]
Yeah, I'm doing this currently with my [COPR](https://copr.fedoraproject.org/coprs/maxamillion/atomic-reactor/) space but this isn't something we can to in EPEL because it will violate the [policy on not overriding core RHEL packages](https://fedoraproject.org/wiki/EPEL/GuidelinesAndPolicies#Policy_for_Conflicting_Packages). Is the plan to maintain this separately? I fear for what might potentially be broken by replacing a core RHEL package.

**Comment by TomasTomecek** [comment]
I've discussed this with docker-py RHEL maintainer and am not sure what was the final statement. CC @lsm5 @arrfab

**Comment by lsm5** [comment]
CentOS SIGs can and do override base packages, I can add a new python-requests along with docker-py and atomic-reactor to the Virt SIG repositories. @maxamillion and @TomasTomecek would you like to be a part of CentOS virt SIG?

RE: RHEL, @TomasTomecek @maxamillion I did patch docker-py earlier so that atomic could run well with an older python-requests. Looks like this would need another patch :\ . I vaguely remember a bug filed to update python-requests on RHEL 7, but can't find it atm :(

**Comment by TomasTomecek** [comment]
@lsm5 I'm actually planning to patch `python-docker-py` in Fedora to don't depend pretty much on any version of `python-requests`: https://github.com/projectatomic/atomic-reactor/issues/226

**Comment by lsm5** [comment]
@TomasTomecek please use @rhatdan's [repo](https://github.com/rhatdan/docker-py/tree/master) instead of original upstream moving forward.

**Comment by TomasTomecek** [comment]
@lsm5 because of https://github.com/rhatdan/docker-py/commit/0fc135c6dbe994aae1530e96071ea9aa33d94c88?

**Comment by maxamillion** [comment]
python-requests got an update in RHEL7 official to 2.6.0 -> `python-requests-2.6.0-1.el7_1.noarch` so now atomic-reactor is erroring the same way Fedora is in https://github.com/projectatomic/atomic-reactor/issues/226

**Comment by bkabrda** [comment]
@maxamillion I already reported this at https://bugzilla.redhat.com/show_bug.cgi?id=1249651 and am waiting for a fix there. Feel free to add yourself to CC of that bug to know when this gets fixed.
BTW I believe the correct fix is pinning the dependencies in the specfile precisely the same way they are pinned in upstream. Then the package will fail to install if dependencies change (and even some compose tools may throw errors about unsatisfied dependencies). When the versions are pinned, then it's only a matter of patching upstream requirements (and the code) for dependencies that have different version in RHEL7/EPEL7.

**Comment by lsm5** [comment]
@bkabrda if i'm reading above comment right, if we have python-requests >= 2.5.3 in the python-docker-py specfile, it will make python-docker-py uninstallable on rhel7 which is just not an option, as there's `atomic` depending on python-docker-py

can't we just upgrade python-requests on rhel7 and move on?

**Comment by lsm5** [comment]
ugh ..re-reading ...so we gotta have python-requests == 2.5.3, hmm :( ...will check on that :( :(

**Comment by bkabrda** [comment]
@lsm5 the point is, that to do packaging correctly, you should do it this way:

1. pin dependencies in the specfile to be precisely the same as dependencies in `requirements.txt`
2. try to install the package
3. see what breaks
4. patch both requirements and the actual code to work with the version that is in RHEL 7
5. profit :)

**Comment by maxamillion** [comment]
this appears to have been resolved, can others verify? if so, I'm good with closing

**Comment by mmilata** [comment]
Seems to be fixed. I can install `python-docker-py` from `rhel7-server-extras-rpms` and `atomic-reactor` from EPEL without problems.
