### ISSUE TITLE
`atomic-reactor` fails on Fedora 22 because of `python-requests` version

### ISSUE THREAD

**Issue by maxamillion** [projectatomic/atomic-reactor#226]
The version of `python-requests` that is in Fedora 22 is too new.

I built an rpm from my git checkout with `tito build --test --builder mock --arg mock=fedora-22-x86_64 --rpm` and then installed the resulting rpm. I get the following error:
```
# atomic-reactor create-build-image --reactor-tarball-path /usr/share/atomic-reactor/atomic-reactor.tar.gz /usr/share/atomic-reactor/images/dockerhost-builder/ buildroot
Traceback (most recent call last):
  File "/usr/bin/atomic-reactor", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.2.1,<2.5.0

# rpm -q python-requests
python-requests-2.7.0-1.fc22.noarch
```

**Comment by TomasTomecek** [comment]
I brought this up with `docker-py` upstream and they said they want to pin version of dependent libs because they experienced breakage in past. Since I'm maintainer of `docker-py` in Fedora, I can patch it to accept any new version of `python-requests`.

**Comment by maxamillion** [comment]
Sounds good, thanks. :+1:

**Comment by TomasTomecek** [comment]
Can you open up bugzilla please?

**Comment by maxamillion** [comment]
There is no `atomic-reactor` component in Fedora bugzilla, what should I file this under?

**Comment by TomasTomecek** [comment]
https://bugzilla.redhat.com/enter_bug.cgi?component=python-docker-py&product=Fedora

**Comment by maxamillion** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1251287

**Comment by bkabrda** [comment]
I left a comment on the bugzilla and also at https://github.com/projectatomic/atomic-reactor/issues/225#issuecomment-128618542 about what I believe is the correct solution.

**Comment by bkabrda** [comment]
atomic-reactor now works on F22, closing
