### ISSUE TITLE
enable injecting arbitrary plugins during build image build

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-reactor#23]
something like:

```
dock create-build-image --plugins-path /var/somewhere
```

In this case, dock would take all plugins from /var/somewhere and put them inside the build image.

Here's how it can be done: clone dock to arbitrary path, copy provided plugins to $dock_path/dock/plugins/, setup.py sdist, ADD dock.tgz...

**Comment by lcarva** [comment]
This can be addressed by using:
```
  --load-plugin [PLUGIN_FILE [PLUGIN_FILE ...]]
                        list of files where plugins live
```
Note, you must pass each plugin file, instead of a directory.
