### ISSUE TITLE
ImportImagePlugin should create ImageStream if it doesn't exist yet

### ISSUE THREAD

**Issue by bkabrda** [projectatomic/atomic-reactor#248]
See https://github.com/projectatomic/osbs-client/pull/181#issuecomment-127175198 for reasoning/explanation.

**Comment by twaugh** [comment]
It will need to be given an extra argument for the `dockerImageRepository`.

Also, osbs-client will need to provide API to create an ImageStream.

**Comment by bkabrda** [comment]
So just to clarify, this is the registry passed to osbs-client when invoking build + image name, correct? (For example `registry.foo.com/fedora:22`)

**Comment by bkabrda** [comment]
Also, I think it should accept two arguments - name of imagestream and dockerimagerepository.

**Comment by twaugh** [comment]
Oh, right, because we're not putting an `imagestream` label in the BuildConfig metadata any more.
