### ISSUE TITLE
Changes for CheckRebuildPlugin to satisfy osbs-client#181

### ISSUE THREAD

**Issue by bkabrda** [projectatomic/atomic-reactor#249]
The `CheckRebuildPlugin` should:
- be renamed to `CheckAndSetRebuildPlugin`
- check if this is autorebuild (received label value is `"false"` (string, since Openshift can't use booleans as label values); if so, it should <do some stuff>
- if not, then set the received label to received value (which is always going to be `"true"` (again, string), when invoked through osbs-client).

Note: it's necessary to check `build_json["metadata"]["labels"]`, not just `build_json["metadata"]` for the labels!

**Comment by twaugh** [comment]
Now we need `OSBS.set_label_on_buildconfig()` :-)
