### ISSUE TITLE
Build atomic-reactor for EPEL7

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/atomic-reactor#273]
Lets try building it again for EPEL7 as its seems the issues are resolved now for atomic-reactor.
@bkabrda Raising an new issue to track it as the old issue #213 is closed now.

**Comment by bkabrda** [comment]
@LalatenduMohanty the fixed packages still haven't reached EPEL 7 repos. I'll build atomic-reactor when they do.

**Comment by mmilata** [comment]
Should be available in EPEL7 now: http://koji.fedoraproject.org/koji/packageinfo?packageID=20745
