### ISSUE TITLE
squashing: provide id of base image to the tool

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-reactor#288]
so it will squash just the built image, not multiple layers from base image

**Comment by jpopelka** [comment]
Isn't this rather a osbs-client issue ?
I mean, the squash plugin already knows how to squash from particular layer/image id.
It's just that 'something' doesn't specify the id when using the squash plugin.
And the 'something' is osbs-client, isn't it ?

**Comment by jpopelka** [comment]
So I think this should be added to the squash plugin:
if the id (`from_layer` arg) hasn't been specified, squash from base_image layer

**Comment by TomasTomecek** [comment]
The thing is that most of the time it is undesirable to figure out id of base image to provide to `from_layer`. Therefore I would be in favor of adding new option `from_base` and set it to `True` by default.

**Comment by jpopelka** [comment]
And what if `from_base` and `from_layer` are specified at the same time ? Should that be an error ?

**Comment by jpopelka** [comment]
And if it's undesirable *most of the time* then it should probably be set to `False` by default ?

**Comment by jpopelka** [comment]
We can discuss it further in #292
