### ISSUE TITLE
Recently added plugins require osbs(-client)

### ISSUE THREAD

**Issue by jpopelka** [projectatomic/atomic-reactor#297]
specifically `post_import_image.py` & `pre_check_and_set_rebuild.py`

Not sure in which sub-package are they supposed to be shipped, but the spec file should be amended to either:
a)  add them to `%files -n python[3]-atomic-reactor-metadata` which already requires `osbs`
b)  add `Requires: osbs` to `%package -n python[3]-atomic-reactor`

**Comment by twaugh** [comment]
My fault. I'd added `osbs` to `images/*/Dockerfile` instead of to the spec file.

**Comment by twaugh** [comment]
Maybe we should add a `rebuilds` sub-package and move them there, along with the `bump_release` plugin and its `python-pygit2` dependency.

**Comment by jpopelka** [comment]
`rebuilds` sub-package sounds OK to me.

**Comment by jpopelka** [comment]
Tim, there's a rebuilds-sub-package branch with such a subpackage.
I tested it and it works. Not sure (after seeing the discussion about removing the pygit2 dependency) if we still want it however.

**Comment by twaugh** [comment]
I think that's still a useful thing to have.
