### ISSUE TITLE
Plug-in for submitting build using Content Generator API

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic-reactor#307]
We need a plug-in for submitting successful builds to koji using the Content Generator API.

Further reading:
https://fedoraproject.org/wiki/Koji/ContentGenerators

Needs to:
 - [x] find container ID of buildroot (https://github.com/projectatomic/osbs-client/pull/239)
 - [x] find OSBS host (not buildroot container) operating system and arch
 - [x] fill in extra output 'docker' fields correctly
 - [x] call the XMLRPC API method

**Comment by twaugh** [comment]
See https://github.com/projectatomic/atomic-reactor/compare/master...koji_promote for work-in-progress.

**Comment by twaugh** [comment]
Requires a fix for https://github.com/projectatomic/osbs-client/issues/238.

**Comment by twaugh** [comment]
Anyone have any better idea to get the OSBS host operating system and arch than running `cat /host/etc/os-release` in a new container with a `/:/host` volume map? (Hope so...)

**Comment by twaugh** [comment]
Let's see if `docker.Client().info()['OperatingSystem']` is good enough.

**Comment by bkabrda** [comment]
@twaugh how about:

```
import platform
arch = platform.machine()  # arch = 'x86_64'
distro = platform.dist()  # distro = ('fedora', '22', 'Twenty Two')
```

For the most part, the platform module just parses some files like `/etc/os-release`, but at least it does it in a very robust and reliable way (always worked fine for me).

**Comment by bkabrda** [comment]
(...and it's been part of Python's stdlib since 2.3: https://docs.python.org/2/library/platform.html)

**Comment by twaugh** [comment]
@bkabrda: It's no good: we need to know the operating system of the *host* machine, not of the container.

**Comment by bkabrda** [comment]
Ahha, I missed that. In that case I think we're on our own :/ (just a side note - it may be interesting to extend the platform module to allow specifying `root` argument to every function, which would then be prefixed to all the paths currently used)

**Comment by twaugh** [comment]
Fixed e.g. #365.
