### ISSUE TITLE
use autoversion client of docker-py

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-reactor#309]
- [ ] ensure it's available in version of docker-py in rhel

https://github.com/docker/docker-py/blob/2dfab762241fa5f9d88dc785cf7fcf0a3e2dff8a/docker/client.py#L893

**Comment by jpopelka** [comment]
> ensure it's available in version of docker-py in rhel

The autoversion client has been part of docker-py since 1.1.0.
AFAICT RHEL-7 has 1.2.3, but epel-6 has 0.7.1.
