### ISSUE TITLE
Support "import" for base image creation from an input tarball

### ISSUE THREAD

**Issue by imcleod** [projectatomic/atomic-reactor#346]
Per a brief conversation with Tomas.

It would be nice to have the ability to use the "docker in docker" functionality of reactor to generate base images using an arbitrary docker version by way of the import command (and possibly docker save as well).  The workflow would be, roughly:

1) Specify details of the docker-running-container we want to use
2) Input a tarball and a docker import command line
3) Take the resulting import and either push it to a registry or save it as a single-file base image representation

**Comment by vrutkovs** [comment]
This is implemented in https://github.com/projectatomic/atomic-reactor/pull/481
