### ISSUE TITLE
take care of releasing

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-reactor#37]
give tito one last chance (because it looks like it just doesn't work smoothly)
if it doesn't work, create script for releasing:
 - [ ] tag last commit
 - [ ] bump spec
 - [ ] bump setup.py
 - [ ] Push to pypi
 - [x] Build in dockerhub

**Comment by bkabrda** [comment]
So I set up the automatic builds at Dockerhub at https://registry.hub.docker.com/u/slavek/buildroot/. The only downside is that when we want to build an image from a tag, we'll have to go there and do it manually. There's no way to automate this AFAICS.

**Comment by bkabrda** [comment]
After we moved under projectatomic, I started building images under https://registry.hub.docker.com/u/slavek/atomic-reactor/. Interestingly enough, it seems that dockerhub fetched an old readme that existed prior to rename (dbuildservice/dock). I'm not sure if that will get updated or not...
Anyway, do we want to close #44 or do we want to also provide atomic-reactor image under projectatomic on dockerhub?

**Comment by bkabrda** [comment]
Automatic releases were set up in #222. Closing.
