### ISSUE TITLE
add_labels_in_df: comprehensive tests for label aliases

### ISSUE THREAD

**Issue by mmilata** [projectatomic/atomic-reactor#388]
There is quite a lot of combinations of old/new labels being set in base image or dockerfile. We should probably raise an error in some pathological cases.

Assuming there's an alias `O → N`, the following table should list all possibilities of the label values in base image and Dockerfile (df include both labels explicitly in Dockerfile and those received as a plugin argument):

base O | base N | df O | df N | action | result O | result N
-------|--------|------|------|--------|----------|---------
- | - | - | - | log.debug alias not applied     | - | -
- | - | - | A | log.debug alias not applied     | - | A
- | - | A | - | add `LABEL N=A`                 | A | A
- | - | A | A | log.debug label already exists  | A | A
- | - | A | B | log.warn should have same value | A | B
- | A | - | - | log.debug alias not applied     | - | A
- | A | - | A | log.debug alias not applied     | - | A
- | A | - | B | log.debug alias not applied     | - | B
- | A | A | - | add `LABEL N=A`                 | A | A
- | A | B | - | add `LABEL N=B`                 | B | B
- | A | A | A | log.debug label already exists  | A | A
- | A | A | B | log.warn should have same value | A | B
- | A | B | A | log.warn should have same value | B | A
- | A | B | B | log.debug label already exists  | B | B
- | A | B | C | log.warn should have same value | B | C
A | - | - | - | add `LABEL N=A`                 | A | A
A | - | - | A | log.debug label already exists  | A | A
A | - | - | B | log.warn should have same value | A | B
A | - | A | - | add `LABEL N=A`                 | A | A
A | - | B | - | add `LABEL N=B`                 | B | B
A | - | A | A | log.debug label already exists  | A | A
A | - | A | B | log.warn should have same value | A | B
A | - | B | A | log.warn should have same value | B | A
A | - | B | B | log.debug label already exists  | B | B
A | - | B | C | log.warn should have same value | B | C
A | A | - | - | add `LABEL N=A`                 | A | A
A | A | - | A | log.debug label already exists  | A | A
A | A | - | B | log.warn should have same value | A | B
A | A | A | - | add `LABEL N=A`                 | A | A
A | A | B | - | add `LABEL N=B`                 | B | B
A | A | A | A | log.debug label already exists  | A | A
A | A | A | B | log.warn should have same value | A | B
A | A | B | A | log.warn should have same value | B | A
A | A | B | B | log.debug label already exists  | B | B
A | A | B | C | log.warn should have same value | B | C
A | B | - | - | add `LABEL N=A` **(?)**             | A | A
A | B | - | A | log.debug label already exists  | A | A
A | B | - | B | log.warn should have same value | A | B
A | B | - | C | log.warn should have same value | A | C
A | B | A | - | add `LABEL N=A`                 | A | A
A | B | B | - | add `LABEL N=B`                 | B | B
A | B | C | - | add `LABEL N=C`                 | C | C
A | B | A | A | log.debug label already exists  | A | A
A | B | A | B | log.warn should have same value | A | B
A | B | A | C | log.warn should have same value | A | C
A | B | B | A | log.warn should have same value | B | A
A | B | B | B | log.debug label already exists  | B | B
A | B | B | C | log.warn should have same value | B | C
A | B | C | A | log.warn should have same value | C | A
A | B | C | B | log.warn should have same value | C | B
A | B | C | C | log.debug label already exists  | C | C
A | B | C | D | log.warn should have same value | C | D

**Comment by mmilata** [comment]
Does the table above seem alright? @twaugh, @TomasTomecek?

**Comment by TomasTomecek** [comment]
This is immensely impressive. I have nothing to add.

**Comment by jpopelka** [comment]
LGTM

**Comment by twaugh** [comment]
Really impressive!

```
A 	- 	- 	B 	log.warn should have same value 	A 	B
```

Not sure this one is right is it? The base image has the old label saying A, and the Dockerfile is trying to override it with B using the new label, but the resulting image has conflicting values depending on whether you look at the old name or the new name.

Same with this one:

```
A 	A 	- 	B 	log.warn should have same value 	A 	B
```

Or are these tests that will change at some point?

**Comment by mmilata** [comment]
The table mostly documents current behaviour which never replaces the old label. We definitely can change it, I think it makes sense in this case.

**Comment by mmilata** [comment]
It looks like we won't be using the feature soon (or ever) so I added a commit to #389 to not use it by default. PTAL, we can modify the algorithm to add old labels with new values (which would fix the two cases mentioned above) if we eventually decide to use it.
