### ISSUE TITLE
tag_and_push: support push with authentication

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic-reactor#404]
When pushing to a registry that requires login, the `tag_and_push` plugin will need to call `docker.Client.login()` to provide the username, email, and password.

We should have `tag_and_push` accept a `registry_secret_path` optional configuration parameter.

If the parameter is set, and has 'username', 'email', and 'password' keys, it should call `login()` using those values before pushing.

**Comment by twaugh** [comment]
@maxamillion

**Comment by vrutkovs** [comment]
Fixed via https://github.com/projectatomic/atomic-reactor/pull/466 and
