### ISSUE TITLE
Make sure unit tests run fine without network access

### ISSUE THREAD

**Issue by mmilata** [projectatomic/atomic-reactor#405]
Currently running unit tests at rpmbuild-time fails because ~17 of them try to clone repo from github.

**Comment by TomasTomecek** [comment]
maybe we could decorate with `@requires_network` and run the suite as `--without=requires_network`.

I think pytest supports something like this.

**Comment by jpopelka** [comment]
Or something like https://github.com/projectatomic/osbs-client/commit/bd7d0b5267e1ad3403a470b8923bf40b03c21633

**Comment by TomasTomecek** [comment]
@jpopelka looks great (but if we know that build in koji is without internet access we don't need to try to create ~17 connections -- not sure if they timeout or die immediately)

**Comment by jpopelka** [comment]
It can be a `@pytest.fixture(scope="module")` so it'd be tested only once, see https://pytest.org/latest/fixture.html#sharing-a-fixture-across-tests-in-a-module-or-class-session
