### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic-reactor#428]
Some tweakable configuration parameters don't necessarily make sense to be in the build JSON, e.g. timeouts.

If we had a configuration file, tweaking parameters like that would be a case of using a different build image rather than having to change osbs.conf on the builder client.

**Comment by TomasTomecek** [comment]
#333 looks very related

definitely a +1 on this; I feel like we should be able to remove persistent configuration from osbs.conf  (or even get rid of osbs.conf completely and let koji pass only runtime configuration (e.g. image name, git) and persistent stuff (labels, hostnames) could live in the build image))

**Comment by twaugh** [comment]
Oh, right, really this is a duplicate of #333 then. Somehow I didn't spot that one.
