### ISSUE TITLE
koji_promote: always run when configured

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic-reactor#435]
The `koji_promote` plugin should run regardless of whether it is inside an explicit build or an automated rebuild.

In other words, the `is_rebuild()` check should be removed.

This change is part of the new scheme for Koji integration, in which the Koji Build object is always created by CG import from atomic-reactor.

CC @maxamillion

See also
* https://github.com/projectatomic/osbs-client/issues/366
* https://github.com/release-engineering/koji-containerbuild/issues/27

**Comment by maxamillion** [comment]
We need to think of a way to handle scratch builds since Koji Content Generators don't have a way to accomplish this. I'm working on a proposal in a branch now, will update when I have something.

**Comment by twaugh** [comment]
Fixed via #445.
