### ISSUE TITLE
post_tag_by_labels: 'scratch' arg to disable primary tag

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic-reactor#441]
For scratch builds we should avoid using the primary tags for the build and instead only use the unique image tag.

To achieve this, the post_tag_by_labels plugin could have a new 'scratch' argument, a Boolean indicating whether this is for a scratch build. When set, the primary tags should not be added.

**Comment by twaugh** [comment]
CC @maxamillion

**Comment by vrutkovs** [comment]
This is implemented via `unique_only_tag` option in https://github.com/projectatomic/atomic-reactor/pull/466
