### ISSUE TITLE
Use pigz in layer dedup code in pulp_push plugin

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/atomic-reactor#464]
We use gzip there, instead we should use ```pigz``` if available

**Comment by twaugh** [comment]
Not so sure it's a straight-forward as this. Using pigz will have an impact on other running builds.

**Comment by vrutkovs** [comment]
Right, we should use the same method as we do for ```compress``` plugin - and fallback to gzip if none is used

**Comment by twaugh** [comment]
Actually I think we should set this to gzip regardless. Pulp can only handle gzip compression, not lzma.

Whereas we might well want to use lzma compression for the tarball that gets uploaded to Koji.

**Comment by vrutkovs** [comment]
Yep, the deduped image is uploaded to pulp only, koji will reuse the image produced by ```compress``` plugin.

Closing this one and keeping #470 open in case pulp will start supporting other formats (or we want to experiment with pigz)
