### ISSUE TITLE
[WIP] tag_and_push should support authentication

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/atomic-reactor#465]

**Comment by mmilata** [comment]
Should we perhaps store the credentials as OpenShift secret instead of sending it to atomic-reactor?

https://docs.openshift.com/enterprise/3.1/dev_guide/image_pull_secrets.html#allowing-pods-to-reference-images-from-other-secured-registries

**Comment by vrutkovs** [comment]
Right, otherwise the token will be stored in the logs

**Comment by twaugh** [comment]
Should we be using a 'push secret' for this?

**Comment by vrutkovs** [comment]
Docker-py doesn't allow passing a conf file for push (although it does allow it for pull).

TODO:
 * [ ] Make sure we can push with login/email/password
 * [ ] Use Openshift secrets to store this in a secret
 * [ ] Rewrite the code to use secret instead of plain config vars
