### ISSUE TITLE
pre_return_dockerfile plugin should be removed

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/atomic-reactor#475]
Its not doing anything useful and `CpDockerfilePlugin` class already exists in `pre_cp_dockerfile` plugin

**Comment by twaugh** [comment]
Agreed. Need to wait until we're sure no osbs-client configurations in use are still expecting it to exist before we remove it.

(For this sort of change, once we have automated rebuilds enabled we'll *additionally* have to wait until we're sure no BuildConfigs still expect an old interface before we remove that interface.)

**Comment by vrutkovs** [comment]
I guess we should take of this before we get chained rebuilds ready - as currently BuildConfigs are safe to be overwritten
