### ISSUE TITLE
Add single source for koji auth configuration

### ISSUE THREAD

**Issue by lcarva** [projectatomic/atomic-reactor#478]
Currently, every plugin that needs an authenticated session with Koji, requires auth specific attributes to be configured on each plugin (SSL Certs Dir, Kerberos Principal, etc). This is not ideal since the same exact configuration needs to be duplicated within the same config file.

A possible solution is to introduce a new plugin that provides an authenticated koji session that can be used by other plugins. This would be achieved by returning an object from its `run` method. The object would then be accessed via DockerBuildWorkflow.prebuild_results.

**Comment by twaugh** [comment]
The same approach could be used for authenticating to the OpenShift server.

**Comment by twaugh** [comment]
We'll have to do this in stages:
- [ ] add the plugin(s) and make existing plugins use them only if the new ones were run (but carry on as currently if not)
- [ ] release atomic-reactor
- [ ] once this is in use everywhere, adjust osbs-client's prod_inner.json so it runs the new plugins

**Comment by lcarva** [comment]
Also could be used for authenticating to Pulp, or probably any external service.

Maybe this should be a new type of plugin, `ProviderPlugin`? These would run prior to pre_build plugins.

So we'd have: `KojiProviderPlugin`, `PulpProviderPlugin`, and `OsbsProviderPlugin`.

And accessing them could be:

```python
try:
    koji_session = self.workflow.providers[KojiProviderPlugin.key].create_session()
except KeyError:
    koji_session = ... # Old way of creating session
```

We could add some wrappers to make it a little nicer to access.

**Comment by lcarva** [comment]
Approach suggested in https://github.com/projectatomic/atomic-reactor/issues/687 is a cleaner, less intrusive approach.
