### ISSUE TITLE
Dockerfile refers to 'latest' which is not really a version.

### ISSUE THREAD

**Issue by gbraad** [projectatomic/atomic-reactor#547]
In the `Dockerfile`  it says `FROM fedora:latest`. This is not really pointing to a version. It might lead to breaking builds if automation is used. Although, fixing to a version means this file needs to be edited on each subsequent release of Fedora. 

What would you saw about changing this to `FROM fedora:24` ?

**Comment by vrutkovs** [comment]
+1 from me

**Comment by gbraad** [comment]
Proposed a PR: #548

**Comment by lcarva** [comment]
+1

**Comment by gbraad** [comment]
I will take care of some other fixes as well, like using `dnf` instead of `yum`, fix using `/tmp/dock` and such...

**Comment by gbraad** [comment]
#548 decided to leave as-is
