### ISSUE TITLE
Enable overwriting json from commandline

### ISSUE THREAD

**Issue by l-d-j** [projectatomic/atomic-reactor#57]
Dock "build" command as is can take arguments  like --image, --git-path. But when I use json and these parameter they are just ignored. I would expect that they will override/complement missing stuff in json.

so if I run 
dock --verbose build --image jboss-base:13 --method here --json build.json

I expect to have image named jboss-base:13

**Comment by bkabrda** [comment]
This is now possible with

```
atomic-reactor build json --method here build.json --substitute image=jboss-base:13
```

Feel free to reopen if this doesn't work for you or you hit an issue using this approach.
