### ISSUE TITLE
atomic-reactor should remove a container if dockerbuild stage has failed

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/atomic-reactor#575]
Atomic-reactor leaves a container in 'Created' state if dockerbuild has failed, which clutters the nodes. AR should be able to remove those automatically

**Comment by twaugh** [comment]
How could this be implemented? Would we have to parse the output from the build call to work out which container was started? What about intermediate images?

What about timing out builds that take longer than a certain time (e.g. if some build is stuck in a loop)?

**Comment by vrutkovs** [comment]
There are three possible ways to solve this:

1. Docker-py claims to have `forcerm` option to remove intermediate containers even on unsuccessful build.

2. Parse the command output and remove the intermediate container IDs

3. Run various cleanup procedures after the build is finished - remove existed containers or dangling images. This might be dangerous though, if other builds are running on that node.

Another issue should be filed for stuck builds
