### ISSUE TITLE
GPG checking is disabled in pre_add_yum_repo.py

### ISSUE THREAD

**Issue by ktdreyer** [projectatomic/atomic-reactor#588]
`atomic_reactor/plugins/pre_add_yum_repo.py` hardcodes the following line that disables GPG checking:

```
'gpgcheck': 0,
```

What are the blockers (in other projects?) to making this enabled, instead?

For example, could we have an optional `gpgkey` parameter to `AddYumRepoPlugin()`, and it would take a URL to a GPG key? If that parameter is `None`, `gpgcheck` can stay as `0`, but otherwise we'd configure that key and set `gpgcheck` to `1` instead.

Here are some example parameters that users could pass in for a gpgkey:

- `gpgkey='file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch'` - Enable GPG checking on Fedora GA packages

- `gpgkey='file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release'` Same thing, but for RHEL GA packages

- `gpgkey='file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-$releasever'` Same thing, but for CentOS GA packages

- `gpgkey='https://internal.example.com/keys/RPM-GPG-KEY-internalbuild'` Enable GPG checking with a particular GPG key (in other words, one that is not Red Hat's gold-signing key :)

**Comment by lcarva** [comment]
> we'd configure that key

What exactly is the process for that? If we're using `rpm --import <gpg-key>`, it would require dynamic changes in Dockerfile.

**Comment by ktdreyer** [comment]
If yum sees a `gpgkey` URL parameter defined for a repository (as described above), then the first `yum -y install` operation that pulls a package from that repository will also add that key as a trusted key to rpmdb.

```
# yum -y install foobar

[ ... lots of output snipped ...]

Retrieving key from http://internal.example.com/keys/RPM-GPG-KEY-internalbuild
Importing GPG key 0xFF00FF00FF:
 Userid     : "Example, Inc. (internal build key) <security@example.com>"
 Fingerprint: ff00 ff00 ff00 ff00 ff00 ff00 ff00 ff00 ff00 ff00
 From       : http://internal.example.com/keys/RPM-GPG-KEY-internalbuild
```

In other words, this should be seamless. There's no need to explicitly run `rpm --import` because yum does the import automatically.

**Comment by lcarva** [comment]
Ah! So if a gpgkey is given to `AddYumRepoPlugin()`, it'll add **both** `gpgkey='<path>' ` and `gpgcheck=1` to the yum repo file.

**Comment by ktdreyer** [comment]
Right!

**Comment by athos-ribeiro** [comment]
The `pre_add_yum_repo.py` plugin was obsolete and was removed in bdf55a6.

**Comment by ktdreyer** [comment]
ODCS has the same problem, so I've filed https://pagure.io/odcs/issue/306 for that.
