### ISSUE TITLE
Atomic-reactor should remove unsupported characters from username when build image name is composed

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/atomic-reactor#681]
atomic-reactor currently fails the build if the produced image has non-docker-compatible chars (e.g. underscore).

This is fine in case of the component, but might happen in case of username. Asking a user to change is not a good idea generally - instead we should filter out the bad chars when the build is submitted

**Comment by lcarva** [comment]
This should be addressed in referenced osbs-client issue.
