### ISSUE TITLE
Error parsing reference: "cqi_/s2i-base:f25-docker-candidate-20170412095735" is not a valid repository/tag

### ISSUE THREAD

**Issue by tkdchen** [projectatomic/atomic-reactor#682]
I made made a buildContainer in Koji. It failed and got an error as per subject. My username ``cqi`` is replaced wtih ``cqi_``.

Task: https://koji.fedoraproject.org/koji/taskinfo?taskID=18945278

**Comment by twaugh** [comment]
This replacement happens in osbs-client: https://github.com/projectatomic/osbs-client/issues/552
