### ISSUE TITLE
Cannot build from scratch images with Koji/OSBS/atomic-reactor

### ISSUE THREAD

**Issue by nipakoo** [projectatomic/atomic-reactor#698]
Unable to build with base image set to 'scratch' utilizing Koji, OSBS and atomic-reactor tool set at least without OSBS configuration adaptations. Would like to have atomic-reactor libary to recognize the special properties of a scratch image and adapt to the limitations that this sets i.e. we cannot perform all the checks and fetch same metadata as with other base images.

**Comment by twaugh** [comment]
This should be fixed on the master branches (and in the latest releases) now.
