### ISSUE TITLE
Race condition when pulling parent image

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic-reactor#881]
In order to avoid a race condition when pulling the parent image, we tag the image with the name of the OpenShift build:
https://github.com/projectatomic/atomic-reactor/blob/1.6.28/atomic_reactor/plugins/pre_pull_base_image.py#L88-L94

However,  we don't use this as the name of the base image in the workflow:
https://github.com/projectatomic/atomic-reactor/blob/1.6.28/atomic_reactor/plugins/pre_pull_base_image.py#L121

Because of this, inspecting the base image later may fail, for example here:
https://github.com/projectatomic/atomic-reactor/blob/1.6.28/atomic_reactor/plugins/pre_inject_yum_repo.py#L158

This is because, meanwhile, some other build using the same parent image may have deleted it:
https://github.com/projectatomic/atomic-reactor/blob/1.6.28/atomic_reactor/plugins/exit_remove_built_image.py#L49-L50

I think the fix is for the pull_base_image plugin to have this line changed:
https://github.com/projectatomic/atomic-reactor/blob/1.6.28/atomic_reactor/plugins/pre_pull_base_image.py#L121
to something like:
```
self.workflow.builder.set_base_image(buildid_base_image.to_str())
```

and to remove these unnecessary lines:
https://github.com/projectatomic/atomic-reactor/blob/1.6.28/atomic_reactor/plugins/pre_pull_base_image.py#L115-L119

**Comment by vrutkovs** [comment]
`set_base_image` was changed recently to have a correct base image name written to annotations. This is useful for osbs-metrics script.

Perhaps this change should be reverted - there is only one place where "real" base image name is used, so instead we should be storing this somewhere in `workflow.builder` and change annotation plugin to read it instead

**Comment by twaugh** [comment]
Yes, that makes sense.

**Comment by twaugh** [comment]
As an alternative:
For dependency graphing we should probably use the Koji build metadata to assemble the inheritance tree for each build which is not itself a parent build. If we do that instead of inspecting Build annotations, we wouldn't need to keep the "real" base image name around at all -- we could instead just no longer record base-image-name.
