### ISSUE TITLE
Rename can_fail variable in plugins

### ISSUE THREAD

**Issue by goldmann** [projectatomic/atomic-reactor#92]
Currently you use the `can_fail` name for variable that specifies if the plugin can fail the build or not, but there is a problem with the name which makes it **very** confusing, it has two meanings:

1. can fail - it can safely fail, we don't care
2. can fail - watch out, it can fail the build, be prepared!

**Comment by TomasTomecek** [comment]
what do you suggest then?

**Comment by goldmann** [comment]
Maybe `plugin_is_allowed_to_fail`? Or `allowed_to_fail`?

**Comment by TomasTomecek** [comment]
`is_allowed_to_fail` looks good to me. What does other think? @twaugh @mmilata @jpopelka @bkabrda

**Comment by l-d-j** [comment]
Maybe if I look at #110 so we can solve both if plugin will have options like:
1) run always
2) run only when any plugin before failed
3) run only when all previous plugins succeeded
So in this way you can define plugins which are vital for your build or plugins which should clean stuff after error. And there will be no need for can_fail option.

**Comment by bkabrda** [comment]
+1 on `is_allowed_to_fail`

**Comment by jpopelka** [comment]
I'm fine with `is_allowed_to_fail`

**Comment by TomasTomecek** [comment]
@l-d-j 
I feel like that such option would cause confusion. I would greatly prefer multiple boolean options rather than one single enum.

**Comment by twaugh** [comment]
`is_allowed_to_fail` +1

**Comment by mmilata** [comment]
I like `allowed_to_fail` better but `is_allowed_to_fail` is fine too:)
